#!/bin/bash

NAME="mysite_app" # Name of the application
DJANGODIR=/home/share/vod # Django project directory
SOCKFILE=/run/vod/gunicorn.sock # we will communicte using this unix socket
PID_FILE=/run/vod/vod.pid
USER=tongshi # the user to run as
GROUP=tongshi # the group to run as
NUM_WORKERS=4 # how many worker processes should Gunicorn spawn
TIME_OUT=900 #set time out!!!!!
DJANGO_SETTINGS_MODULE=mysite.settings # which settings file should Django use
DJANGO_WSGI_MODULE=mysite.wsgi # WSGI module name
APP=/home/share/vod/env/bin/gunicorn
echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ./env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $APP ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--worker-class gevent \
--timeout=$TIME_OUT \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=- \
--reload \
--pid $PID_FILE \
