# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0002_auto_20170413_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custome_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 5, 54, 31, 339786, tzinfo=utc)),
        ),
    ]
