# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_post_custome_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='custome_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
