# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import vod.models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0005_auto_20170414_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=vod.models.upload_location, width_field='width_field'),
        ),
    ]
