# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 02:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0006_auto_20170414_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='filer.Image'),
        ),
    ]
