# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 03:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('vod', '0007_auto_20170414_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_name', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_name', to='filer.Image'),
        ),
    ]
