# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('isSecret', models.BooleanField(default=False)),
                ('directory', models.FilePathField(path='/home/xjtu')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='videocategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodmanagement.VideoCategoryType'),
        ),
    ]
