# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodmanagement', '0002_auto_20170415_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocategorytype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='My Category Type'),
        ),
    ]
