# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodmanagement', '0003_auto_20170415_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vodmanagement.VideoCategory'),
        ),
        migrations.AddField(
            model_name='vod',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
