# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodmanagement', '0004_auto_20170415_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vod',
            name='file_size',
            field=models.CharField(default='0B', editable=False, max_length=128),
        ),
    ]
