# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vodmanagement', '0005_auto_20170415_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vod',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vod',
            name='type',
            field=models.CharField(choices=[('link', 'LINK'), ('vod', 'VOD')], default='link', max_length=128),
        ),
        migrations.AddField(
            model_name='vod',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='type',
            field=models.CharField(choices=[('common', 'Common'), ('special', 'Special purpose')], default='common', max_length=128),
        ),
    ]
