# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodmanagement', '0006_auto_20170416_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vod',
            name='type',
        ),
        migrations.AlterField(
            model_name='vod',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vod',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
