# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodmanagement', '0007_auto_20170416_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.URLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vodmanagement.VideoCategory')),
            ],
        ),
        migrations.AlterField(
            model_name='filedirectory',
            name='path',
            field=models.CharField(default='/home/xjtu/Desktop/django/mysite/media', max_length=512),
        ),
    ]
